#!/system/bin/sh

# samsung gt-i9100
# dmesg trial and error

# this causes script to exit if any non-zero status returned

# defaults 
: ${YAMIR_INTERFACE:="eth0"}
: ${YAMIR_SSID:="yamir"}
: ${YAMIR_CHANNEL:="6"}
: ${YAMIR_IP_ADDR:="192.168.1.10"}
: ${YAMIR_NETMASK:="255.255.255.0"}

stop()
{
    rmmod dhd
    setprop wlan.driver.status "unloaded"
}

start() 
{
    # 0. turn off normal wifi
    svc wifi disable
    sleep 1

    # 1. start the wifi interface
    insmod /lib/modules/dhd.ko "firmware_path=/system/etc/wifi/bcm4330_sta.bin nvram_path=/system/etc/wifi/nvram_net.txt_murata"
    setprop wlan.driver.status "ok"

    sleep 1

    # 2. configure it
    netcfg $YAMIR_INTERFACE down
    ./iwconfig $YAMIR_INTERFACE mode ad-hoc essid $YAMIR_SSID channel $YAMIR_CHANNEL commit
    netcfg $YAMIR_INTERFACE down
    #./iwconfig $YAMIR_INTERFACE ap 02:ca:ff:ee:ba:be
    # 3. assign ip address to it
    ifconfig $YAMIR_INTERFACE $YAMIR_IP_ADDR netmask $YAMIR_NETMASK up
}

$1
