#cloud-config
hostname: {{VM_NAME}}
datasource_list: [ NoCloud ]

# use lts for kernel modules
packages:
  - alpine-sdk
  - linux-lts
  - linux-lts-dev
  - linux-firmware-rtlwifi
  - wireless-tools
  - wireless-regdb
  - bridge-utils
  - akms
  - zstd
  - libcap-setcap
  - util-linux
  - tcpdump

passwd:
  list: |
    root:alpine
    alpine:alpine
  expire: False

ssh_pwauth: true

# XXX alpine is ignore this
write_files:
  - path: /etc/ssh/sshd_config
    permissions: '0600'
    content: |
      Port 2222
  - path: /etc/ssh/sshd_config.d/00-force-passwords.conf
    permissions: '0600'
    content: |
      PasswordAuthentication yes

users:
  - name: alpine
    lock_passwd: false
    ssh_authorized_keys:
      - "{{SSH_PUBLIC_KEY}}"

runcmd:
  - echo "alpine:alpine" | chpasswd
  - chmod g-s /home/alpine
  - echo 'alias ll="ls -l"' >> /home/alpine/.profile
  - chown alpine:alpine /home/alpine/.profile
  - truncate -s 0 /etc/motd
  - ln -sf /usr/bin/doas /usr/bin/sudo
  - touch /etc/alpine_ready
  - KVER=$(ls -1 /lib/modules | grep "lts" | sort -V | tail -n 1) && depmod -a $KVER && mkinitfs -o /boot/initramfs-lts $KVER
  - sed -i 's/^timeout.*/timeout 2/' /etc/update-extlinux.conf
  - sed -i 's/^default=.*/default=lts/' /etc/update-extlinux.conf
  - sed -i 's/Port 2222/Port 22/' /etc/ssh/sshd_config
  - update-extlinux
  - sync
  - reboot -f
