#cloud-config
hostname: {{VM_NAME}}
datasource_list: [ NoCloud ]

apk_repos:
  preserve_repositories: false
  alpine_repo:
    base_url: https://dl-cdn.alpinelinux.org/alpine
    version: edge
    community_enabled: true
    testing_enabled: true

packages:
  - linux-firmware-rtlwifi
  - wireless-tools
  - wireless-regdb
  - bridge-utils
  - alpine-sdk
  - akms
  - zstd
  - libcap-setcap
  - util-linux
  - tcpdump

passwd:
  list: |
    root:alpine
    alpine:alpine
  expire: False

ssh_pwauth: true

# XXX alpine is ignore this
write_files:
  - path: /etc/ssh/sshd_config.d/00-force-passwords.conf
    permissions: '0600'
    content: |
      PasswordAuthentication yes

users:
  - name: alpine
    lock_passwd: false
    ssh_authorized_keys:
      - "{{SSH_PUBLIC_KEY}}"

runcmd:
  - echo "alpine:alpine" | chpasswd
  - chmod g-s /home/alpine
  - echo 'alias ll="ls -l"' >> /home/alpine/.profile
  - chown alpine:alpine /home/alpine/.profile
  - truncate -s 0 /etc/motd
  - ln -sf /usr/bin/doas /usr/bin/sudo
  - apk update
  - apk add linux-openpax linux-openpax-dev
  - sleep 2
  - mkinitfs -o /boot/initramfs-openpax $(ls /lib/modules | grep openpax)
  - sed -i 's/default=virt/default=openpax/' /etc/update-extlinux.conf
  - update-extlinux

